### ISSUE TITLE
Submit button

### ISSUE THREAD

**Issue by jamsge** [jamsge/codenao-frontend#1]
Create a submit button that sends an HTTP POST request with a JSON payload to the code submission REST API endpoint (`http://localhost:3000/submit` for now). Here's an example of what the JSON might look like:

```json
{
    "language": "python",
    "code": "print(\"Hello world!\")\n# this is my first program :D"
}
```

Add whatever other information might be useful (date? can't think of anything else rn)

**Comment by HaoHuynh0301** [comment]
Hello I think I solve this issue for you. Can you assign me for this ? Thank you @jamsge

**Comment by ZombiMigz** [comment]
40e34f9
