### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by jamsge** [jamsge/codenao-frontend#9]
very very low priority

Eventually if we get far enough, we're going to have more features than just a text editor, submit button, and output textbox. Create a Bootstrap sidebar ([see here](https://getbootstrap.com/docs/5.0/components/offcanvas/#live-demo)) that opens via a button on the navbar ([see here](https://getbootstrap.com/docs/5.0/components/navbar/)). Just need a functioning close button for now.

**Comment by vonet999** [comment]
Assign me . Can i try this

**Comment by jamsge** [comment]
Complete as of https://github.com/jamsge/codenao-frontend/commit/84d5257286b080138877811d9f4e0b5faed86ef1. 

@vonet999 Sorry I saw this late, DM me on discord (jams#1008) so I can get you into our chat.
